FROM node:8
ENV PORT 443
EXPOSE 443
COPY package.json /usr/src/match-three/
COPY yarn.lock /usr/src/match-three/
WORKDIR /usr/src/match-three
RUN yarn install
VOLUME /usr/src/match-three/node_modules
CMD npm run dev
